// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetWebProg.Data;

#nullable disable

namespace ProjetWebProg.Migrations
{
    [DbContext(typeof(ProjetWebProgContext))]
    [Migration("20260408133023_creationBdToutout")]
    partial class creationBdToutout
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetWebProg.Data.Toutous", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NbrInventaire")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Prix")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Toutous");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Ours en peluche brun classique",
                            Image = "bernard.jpg",
                            NbrInventaire = 10,
                            Nom = "Bernard",
                            Prix = 25
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lapin blanc aux longues oreilles",
                            Image = "lulu.jpg",
                            NbrInventaire = 15,
                            Nom = "Lulu",
                            Prix = 30
                        },
                        new
                        {
                            Id = 3,
                            Description = "Chat gris rayé tout doux",
                            Image = "felix.jpg",
                            NbrInventaire = 8,
                            Nom = "Félix",
                            Prix = 20
                        },
                        new
                        {
                            Id = 4,
                            Description = "Licorne rose avec crinière arc-en-ciel",
                            Image = "rosie.jpg",
                            NbrInventaire = 12,
                            Nom = "Rosie",
                            Prix = 35
                        },
                        new
                        {
                            Id = 5,
                            Description = "Chien beige avec grandes pattes",
                            Image = "maxou.jpg",
                            NbrInventaire = 6,
                            Nom = "Maxou",
                            Prix = 28
                        },
                        new
                        {
                            Id = 6,
                            Description = "Poisson clown orange et blanc",
                            Image = "nemo.jpg",
                            NbrInventaire = 20,
                            Nom = "Nemo",
                            Prix = 22
                        },
                        new
                        {
                            Id = 7,
                            Description = "Éléphant gris avec nœud rose",
                            Image = "bella.jpg",
                            NbrInventaire = 5,
                            Nom = "Bella",
                            Prix = 40
                        },
                        new
                        {
                            Id = 8,
                            Description = "Petit pingouin noir et blanc rigolo",
                            Image = "coco.jpg",
                            NbrInventaire = 14,
                            Nom = "Coco",
                            Prix = 18
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
